# Generated by Django 4.0.3 on 2022-04-10 19:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0004_history_product_historyitem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserProfile',
            new_name='UserMember',
        ),
        migrations.RemoveField(
            model_name='historyitem',
            name='history',
        ),
        migrations.RemoveField(
            model_name='historyitem',
            name='product',
        ),
        migrations.DeleteModel(
            name='History',
        ),
        migrations.DeleteModel(
            name='HistoryItem',
        ),
    ]
