# Generated by Django 4.0.3 on 2022-04-10 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_content_delete_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
