# Generated by Django 4.0.3 on 2022-04-11 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_remove_notes_title_notes_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='user',
        ),
        migrations.AddField(
            model_name='notes',
            name='title',
            field=models.CharField(default=0, max_length=60),
        ),
    ]
