# Generated by Django 4.0.3 on 2022-04-11 00:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0010_remove_notes_user_notes_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notes',
            name='title',
        ),
        migrations.AddField(
            model_name='notes',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notes',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
