# Generated by Django 4.0.3 on 2022-04-11 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_notes_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
    ]
