# Generated by Django 4.0.3 on 2022-04-11 00:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.CharField(default=0, max_length=120),
        ),
    ]
