# Generated by Django 4.0.3 on 2022-04-12 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_delete_usermember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='content',
            field=models.CharField(default=0, max_length=700),
        ),
    ]
