# Generated by Django 4.0.3 on 2022-06-12 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_subscription_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='name',
        ),
    ]
